name: Build and Deploy to VPS

on:
  push:
    branches: [main] # This runs only when you push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Gets the code from your repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Sets up the correct version of Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Installs dependencies and builds the project into a 'dist' folder
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # 4. Securely copies the contents of the 'dist' folder to your VPS
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/" # Copy the entire dist folder
          target: "/var/www/gaia-pms.com/dist"
          strip_components: 1
